# Configuration Supabase locale - DevWeb31 Architecture
# Auteur: DevWeb31
# Version: 1.0.0

# Configuration du projet (requis pour le démarrage local)
project_id = "marie-fortea-local"

[api]
enabled = true
port = 54331
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54332
shadow_port = 54330
major_version = 15

[db.pooler]
enabled = false
port = 54339
pool_mode = "transaction"
default_pool_size = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54333
api_url = "http://localhost:54331"

[inbucket]
enabled = true
port = 54334
smtp_port = 54335
pop3_port = 54336

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[edge_runtime]
enabled = true
