-- Mettre à jour les vues pour inclure les nouveaux champs du formulaire détaillé

-- Mettre à jour la vue active_booking_requests
CREATE OR REPLACE VIEW "public"."active_booking_requests" AS 
SELECT id,
    status,
    created_at,
    updated_at,
    parent_name,
    parent_email,
    parent_phone,
    parent_address,
    service_type,
    requested_date,
    start_time,
    end_time,
    duration_hours,
    children_count,
    children_details,
    children_ages,
    special_instructions,
    emergency_contact,
    emergency_phone,
    preferred_contact_method,
    contact_notes,
    captcha_verified,
    ip_address,
    user_agent,
    source,
    utm_source,
    utm_medium,
    utm_campaign,
    estimated_total,
    deleted_at,
    archived_at,
    status_id,
    detailed_form_token,
    detailed_form_sent_at,
    detailed_form_completed_at
FROM booking_requests
WHERE ((deleted_at IS NULL) AND (archived_at IS NULL));

-- Mettre à jour la vue archived_booking_requests
CREATE OR REPLACE VIEW "public"."archived_booking_requests" AS 
SELECT id,
    status,
    created_at,
    updated_at,
    parent_name,
    parent_email,
    parent_phone,
    parent_address,
    service_type,
    requested_date,
    start_time,
    end_time,
    duration_hours,
    children_count,
    children_details,
    children_ages,
    special_instructions,
    emergency_contact,
    emergency_phone,
    preferred_contact_method,
    contact_notes,
    captcha_verified,
    ip_address,
    user_agent,
    source,
    utm_source,
    utm_medium,
    utm_campaign,
    estimated_total,
    deleted_at,
    archived_at,
    status_id,
    detailed_form_token,
    detailed_form_sent_at,
    detailed_form_completed_at
FROM booking_requests
WHERE ((deleted_at IS NULL) AND (archived_at IS NOT NULL));

-- Mettre à jour la vue deleted_booking_requests
CREATE OR REPLACE VIEW "public"."deleted_booking_requests" AS 
SELECT id,
    status,
    created_at,
    updated_at,
    parent_name,
    parent_email,
    parent_phone,
    parent_address,
    service_type,
    requested_date,
    start_time,
    end_time,
    duration_hours,
    children_count,
    children_details,
    children_ages,
    special_instructions,
    emergency_contact,
    emergency_phone,
    preferred_contact_method,
    contact_notes,
    captcha_verified,
    ip_address,
    user_agent,
    source,
    utm_source,
    utm_medium,
    utm_campaign,
    deleted_at,
    detailed_form_token,
    detailed_form_sent_at,
    detailed_form_completed_at
FROM booking_requests
WHERE (deleted_at IS NOT NULL);

-- Mettre à jour la vue trashed_booking_requests
CREATE OR REPLACE VIEW "public"."trashed_booking_requests" AS 
SELECT id,
    status,
    created_at,
    updated_at,
    parent_name,
    parent_email,
    parent_phone,
    parent_address,
    service_type,
    requested_date,
    start_time,
    end_time,
    duration_hours,
    children_count,
    children_details,
    children_ages,
    special_instructions,
    emergency_contact,
    emergency_phone,
    preferred_contact_method,
    contact_notes,
    captcha_verified,
    ip_address,
    user_agent,
    source,
    utm_source,
    utm_medium,
    utm_campaign,
    estimated_total,
    deleted_at,
    archived_at,
    status_id,
    detailed_form_token,
    detailed_form_sent_at,
    detailed_form_completed_at
FROM booking_requests
WHERE (deleted_at IS NOT NULL);

-- Mettre à jour la vue booking_requests_with_status
DROP VIEW IF EXISTS "public"."booking_requests_with_status";
CREATE VIEW "public"."booking_requests_with_status" AS 
SELECT br.id,
    br.status,
    br.created_at,
    br.updated_at,
    br.parent_name,
    br.parent_email,
    br.parent_phone,
    br.parent_address,
    br.service_type,
    br.requested_date,
    br.start_time,
    br.end_time,
    br.duration_hours,
    br.children_count,
    br.children_details,
    br.children_ages,
    br.special_instructions,
    br.emergency_contact,
    br.emergency_phone,
    br.preferred_contact_method,
    br.contact_notes,
    br.captcha_verified,
    br.ip_address,
    br.user_agent,
    br.source,
    br.utm_source,
    br.utm_medium,
    br.utm_campaign,
    br.estimated_total,
    br.deleted_at,
    br.archived_at,
    br.status_id,
    br.detailed_form_token,
    br.detailed_form_sent_at,
    br.detailed_form_completed_at,
    COALESCE(bs.code, 'pending'::character varying) AS status_code,
    COALESCE(bs.name, 'En attente'::character varying) AS status_name,
    COALESCE(bs.color, '#6b7280'::character varying) AS status_color,
    COALESCE(bs.icon, 'clock'::character varying) AS status_icon,
    COALESCE(bs.description, 'Demande en attente de traitement'::text) AS status_description,
    COALESCE(st.name, 'Service personnalisé'::character varying) AS service_name,
    COALESCE(st.base_price, 20.00) AS base_price
FROM ((booking_requests br
     LEFT JOIN booking_statuses bs ON ((br.status_id = bs.id)))
     LEFT JOIN service_types st ON (((br.service_type)::text = (st.code)::text)))
WHERE (br.deleted_at IS NULL)
ORDER BY br.created_at DESC;
